# Custom latexmk configuration
## Enable shell escape
set_tex_cmds('--shell-escape %O %S');

## Output PDF by default and use LuaLaTeX
$pdf_mode = 4;

## Treat warnings as errors
$warnings_as_errors = 1;
